// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Crumbs: typeof import('./components/content/Crumbs/Crumbs.vue')['default']
    Earth: typeof import('./components/content/Echerts/Earth.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Graph: typeof import('./components/content/Echerts/Graph.vue')['default']
    HeaderTabs: typeof import('./components/content/HeaderTabs/HeaderTabs.vue')['default']
    Icon: typeof import('./components/common/Icon/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeMenu: typeof import('./components/content/TreeMenu/TreeMenu.vue')['default']
  }
}

export {}
